#!/usr/bin/env python3
"""deploy.py — deploy hoover4 from one hoover4.ini.

Stdlib only (configparser, argparse, subprocess, pathlib, os, sys, socket, hashlib,
shutil, stat, re, json, textwrap). Must import clean on python 3.10 and run clean on 3.14:
no tomllib, no ExceptionGroup, no 3.11+ syntax.

Secrets rule: the ini stores host PATHS to key files, never values. Those paths are
rendered into the generated .env as bind-mount sources; a container learns the path,
never the value. No secret value ever enters a .env, a compose file, a log line or a
command line.
"""

import argparse
import configparser
import hashlib
import json
import os
import re
import shutil
import socket
import stat
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).parent.resolve()
INI_PATH = REPO_ROOT / "hoover4.ini"
INI_EXAMPLE_PATH = REPO_ROOT / "hoover4.ini.example"

MAIN_COMPOSE_DIR = REPO_ROOT / "main_services" / "ops" / "docker"
AI_COMPOSE_DIR = REPO_ROOT / "ai_services"

ENV_HEADER = "# GENERATED by deploy.py from hoover4.ini - DO NOT EDIT.\n"

# Volumes whose deletion costs tens of gigabytes of re-download (or the agent's own
# tools). Matched by suffix against compose-project-prefixed volume names.
CACHE_VOLUME_SUFFIXES = ("ai_models_cache", "vllm_huggingface_cache", "easyocr_models_cache")
# Never removed by --reset, even with --reset-caches: killing Serena mid-session
# drops the MCP connection the agent is using to do the work. Its container is kept
# out of the reset's `compose down` by excluding the serena overlay (compose_reset).
PROTECTED_VOLUME_SUFFIXES = ("serena_state",)

CDI_SPEC = "/etc/cdi/nvidia.yaml"

# --------------------------------------------------------------------------------------
# Defaults. Every value here is overridable in hoover4.ini; hoover4.ini.example is a
# fully commented rendering of this table. Ports are ini keys, never code literals —
# the single exception is the website's 12345, which humans type.
# --------------------------------------------------------------------------------------

DEFAULTS = {
    "ai_services": {
        "enabled": "false",
        "host": "127.0.0.1",
        "bind_ip": "0.0.0.0",
        # local LLM: the agent model, served OpenAI-compatible.
        "llm_selfhosted": "false",
        "vllm_port": "21960",
        "vllm_image": "vllm/vllm-openai:v0.17.1",
        "vllm_model": "Qwen/Qwen3.5-35B-A3B",
        "vllm_served_name": "qwen3.5-35b-a3b",
        "vllm_gpu_fraction": "0.50",
        "vllm_max_model_len": "262144",
        "vllm_max_num_seqs": "16",
        "vllm_tool_parser": "qwen3_xml",
        "vllm_reasoning_parser": "qwen3",
        "vllm_api_key_file": "",
        # GPU NER + embeddings
        "ai_server_enabled": "true",
        "ai_server_port": "21961",
        "ner_enabled": "true",
        "embeddings_enabled": "true",
        "embeddings_model": "intfloat/multilingual-e5-small",
        "embeddings_dim": "384",
        "reranker_enabled": "true",
        # Multilingual MS-Marco MiniLM cross-encoder: same calibre as the English-only
        # ms-marco-MiniLM-L-6-v2, but this corpus is not English-only.
        "reranker_model": "cross-encoder/mmarco-mMiniLMv2-L12-H384-v1",
        "half_precision": "true",
        "torch_compile": "false",
        "hf_token_file": "",
        # Per-capability GPU admission. NER saturates at 4; embeddings still scale at 8.
        "ai_server_ner_concurrency": "4",
        "ai_server_embed_concurrency": "8",
        "ai_server_rerank_concurrency": "4",
        # GPU OCR
        "easyocr_enabled": "true",
        "easyocr_port": "21962",
        "easyocr_languages": "en",
    },
    "main_services": {
        # which side of each capability the pipeline prefers
        "ner_provider": "gpu",
        "ner_spacy_enabled": "false",
        "embeddings_provider": "gpu",
        "pdf_ocr_provider": "tesseract",
        "tesseract_cpu_enabled": "true",
        "tesseract_languages": "eng",
        # regex entity scanning — always on, so the only knobs are its size
        "regex_scanner_threads": "10",
        "regex_scanner_queue_depth": "32",
        # How the website is served. false = `dx serve` (the development loop). true =
        # build once with `dx build --release` and serve the binary, which is what a
        # visitor should get: no dev overlay, no rebuild-on-boot 500s. See
        # compose/website-release.yaml.
        "website_release_mode": "false",
        # Search limits. Empty = unset in the rendered env, and the website backend
        # falls back to its own defaults (8 concurrent shard queries, 30 s per query).
        "search_max_parallelism": "",
        "search_timeout_seconds": "",
        "ocr_pdf_enabled": "true",
        # Worker fleet. Empty = the worker's own default, which for the common tier is
        # cores/4 processes of 8 activity slots each and for the rest is shaped by what
        # that tier waits on. Set one only to override a measurement.
        "common_workers": "",
        "common_concurrency": "",
        # Hard memory ceiling for the worker container. Explicit because the fleet's
        # cost is memory: every worker process carries its own interpreter and its own
        # Magika model, so the count and this number have to be chosen together.
        "worker_mem_limit": "29000M",
        "tika_concurrency": "",
        "ocr_concurrency": "",
        "nlp_concurrency": "",
        "embed_concurrency": "",
        "indexing_concurrency": "",
        # How long a shutting-down worker may keep its in-flight activities before they
        # are cancelled. The container's stop grace period is DERIVED from this (see
        # render_main_env) rather than configured beside it, because an SDK grace period
        # longer than the container's is a lie: the runtime kills the process first.
        "worker_graceful_shutdown_seconds": "60",
        # runtime behaviour when the GPU host is unreachable
        "gpu_fallback": "true",
        "gpu_connect_timeout_ms": "2000",
        "gpu_circuit_break_seconds": "60",
        # dev tooling
        "serena_enabled": "true",
        "serena_port": "21940",
        # demo / data
        "demo_mode": "false",
        "testdata_dir": "",
        # Where the dataset-creation form looks for subfolders. An IN-CONTAINER path:
        # `testdata_dir` already decides what the host mounts there, and the form walks
        # one level below this and offers the names -- never a free-text path.
        "datasets_mount_path": "/testdata",
        # shared bearer token between the research agents and the MCP servers
        "mcp_shared_secret_file": "",
        # Interfaces the published ports bind to. 0.0.0.0 keeps a dev box behaving the
        # way it always has; a host with a public IP wants both narrowed, because the
        # website carries no authentication of its own and the infrastructure ports
        # carry none at all.
        "website_bind_ip": "0.0.0.0",
        "infra_bind_ip": "0.0.0.0",
        # ports — main infrastructure
        "clickhouse_http_port": "21900",
        "clickhouse_native_port": "21901",
        "manticore_sql_port": "21902",
        "manticore_http_port": "21903",
        "garage_s3_port": "21904",
        "garage_admin_port": "21905",
        "redis_port": "21906",
        "temporal_grpc_port": "21907",
        "temporal_http_port": "21908",
        "temporal_ui_port": "21909",
        "clickhouse_monitoring_port": "21910",
        "ch_ui_port": "21911",
        "cassandra_port": "21912",
        "elasticsearch_port": "21913",
        # ports — main app services
        "pdf_to_html_port": "21920",
        "tesseract_cpu_port": "21921",
        "ocr_pdf_port": "21922",
        "ner_spacy_port": "21923",
        "embeddings_cpu_port": "21924",
        "regex_entity_scanner_port": "21925",
        "mcp_collections_port": "21930",
        "mcp_metasearch_port": "21931",
        "mcp_browser_port": "21932",
        "mcp_whois_port": "21934",
        "internal_search_agent_port": "21936",
        "full_research_agent_port": "21937",
        # image pins (were env.example)
        "cassandra_version": "3.11.9",
        "elasticsearch_version": "7.17.27",
        "temporal_version": "1.23.1",
        "temporal_ui_version": "2.26.2",
        # A history shard is a single-writer queue, and their number caps every
        # workflow-history write in the deployment no matter how many workers exist.
        # auto-setup's development default of 4 holds the pipeline to about a dozen
        # activity dispatches a second while the workers sit idle. This is FIXED for the
        # life of the persistence store -- see --reset-temporal.
        "temporal_history_shards": "512",
        # Pinned by tag AND manifest-list digest. The LIST digest, not a platform one:
        # pinning the amd64 digest makes the image unresolvable on the aarch64 host.
        "garage_version": "v2.3.0",
        "garage_image_digest":
            "sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690",
        # Declared, not measured: Garage sizes partitions from it and reports the store
        # full past it. A wrong value surfaces as ingest errors hours in, not at deploy.
        "garage_capacity": "300G",
    },
    "llm_provider.selfhosted": {
        "enabled": "false",
        "base_url": "",  # empty = derived: http://<ai_services.host>:<vllm_port>/v1
        "model": "",     # empty = vllm_served_name
        "api_key_file": "",
    },
    "llm_provider.nvidia": {
        "enabled": "true",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "model": "",
        "api_key_file": "",
    },
    "llm_provider.moonshot": {
        "enabled": "false",
        "base_url": "https://api.moonshot.ai/v1",
        "model": "",
        "api_key_file": "",
    },
}

LLM_PROVIDER_SECTIONS = [s for s in DEFAULTS if s.startswith("llm_provider.")]

# Compose overlays per side, in order, with the ini flag that enables them.
AI_OVERLAYS = [
    ("llm_selfhosted", "compose/vllm.yaml", "hoover4-vllm"),
    ("ai_server_enabled", "compose/ai-server.yaml", "hoover4-ai-server"),
    ("easyocr_enabled", "compose/easyocr.yaml", "hoover4-easyocr-gpu"),
]
MAIN_OVERLAYS = [
    (None, "compose/agents.yaml", None),          # always on
    (None, "compose/regex-entity-scanner.yaml", None),  # always on
    ("tesseract_cpu_enabled", "compose/tesseract-cpu.yaml", "hoover4-tesseract-cpu"),
    ("ocr_pdf_enabled", "compose/ocr-pdf.yaml", "hoover4-ocr-pdf"),
    ("ner_spacy_enabled", "compose/ner-spacy.yaml", "hoover4-ner-spacy"),
    # Overrides hoover4-website's command; adds no service of its own.
    ("website_release_mode", "compose/website-release.yaml", None),
]

# Serena is deployed as a SEPARATE compose project (hoover4-devtools), not an overlay
# of the main one: `compose down` removes every container carrying the project label,
# so sharing the project would let `deploy --reset` kill the MCP server the agent is
# talking through. Its volume is likewise prefixed hoover4-devtools_, never hoover4_.
SERENA_OVERLAY = "compose/serena.yaml"
SERENA_PROJECT = "hoover4-devtools"

# Services that request the GPU on the ai side (for the GPU/CDI preflights).
AI_GPU_OVERLAYS = ("compose/vllm.yaml", "compose/ai-server.yaml", "compose/easyocr.yaml")

# (service, ini section, port key) for every port the selected side publishes. Used by
# the port-free preflight; stdlib-only deploy.py cannot parse compose YAML, so the
# table lives here next to the overlay selection that produces it.
MAIN_PUBLISHED = [
    ("clickhouse", "main_services", "clickhouse_http_port"),
    ("clickhouse", "main_services", "clickhouse_native_port"),
    ("manticore", "main_services", "manticore_sql_port"),
    ("manticore", "main_services", "manticore_http_port"),
    ("garage", "main_services", "garage_s3_port"),
    ("garage", "main_services", "garage_admin_port"),
    ("redis", "main_services", "redis_port"),
    ("temporal", "main_services", "temporal_grpc_port"),
    ("temporal", "main_services", "temporal_http_port"),
    ("temporal-ui", "main_services", "temporal_ui_port"),
    ("clickhouse-monitoring", "main_services", "clickhouse_monitoring_port"),
    ("ch-ui", "main_services", "ch_ui_port"),
    ("temporal-cassandra", "main_services", "cassandra_port"),
    ("temporal-elasticsearch", "main_services", "elasticsearch_port"),
    ("hoover4-processing-pdf-to-html", "main_services", "pdf_to_html_port"),
    ("hoover4-website", None, "12345"),  # the one hardcoded port humans type
    ("hoover4-mcp-collections", "main_services", "mcp_collections_port"),
    ("hoover4-mcp-metasearch", "main_services", "mcp_metasearch_port"),
    ("hoover4-mcp-browser", "main_services", "mcp_browser_port"),
    ("hoover4-mcp-whois", "main_services", "mcp_whois_port"),
    ("hoover4-internal-search-agent", "main_services", "internal_search_agent_port"),
    ("hoover4-full-research-agent", "main_services", "full_research_agent_port"),
    ("hoover4-tesseract-cpu", "main_services", "tesseract_cpu_port"),
    ("hoover4-ocr-pdf", "main_services", "ocr_pdf_port"),
    ("hoover4-ner-spacy", "main_services", "ner_spacy_port"),
    ("hoover4-regex-entity-scanner", "main_services", "regex_entity_scanner_port"),
]


class DeployError(Exception):
    pass


def fail(msg):
    raise DeployError(msg)


# --------------------------------------------------------------------------------------
# Config loading
# --------------------------------------------------------------------------------------

class Config:
    def __init__(self, ini_path):
        self.values = {section: dict(keys) for section, keys in DEFAULTS.items()}
        self.extra = {}  # ini keys unknown to DEFAULTS, kept for forward compat
        if ini_path is not None:
            parser = configparser.ConfigParser(inline_comment_prefixes=(";",))
            try:
                with open(ini_path, "r", encoding="utf-8") as fh:
                    parser.read_file(fh)
            except configparser.Error as exc:
                fail("cannot parse %s: %s" % (ini_path, exc))
            for section in parser.sections():
                if section not in self.values:
                    self.values[section] = {}
                    self.extra[section] = []
                for key, value in parser.items(section):
                    value = value.strip()
                    if section in DEFAULTS and key not in DEFAULTS[section]:
                        self.extra.setdefault(section, []).append(key)
                    self.values[section][key] = value

    def get(self, section, key):
        try:
            return self.values[section][key]
        except KeyError:
            fail("unknown config key [%s] %s" % (section, key))

    def get_bool(self, section, key):
        value = self.get(section, key).strip().lower()
        if value in ("1", "true", "yes", "on"):
            return True
        if value in ("0", "false", "no", "off"):
            return False
        fail("[%s] %s must be a boolean, got %r" % (section, key, value))

    def secret_files(self):
        """All (section, key, host_path) for non-empty *_file keys."""
        out = []
        for section, keys in self.values.items():
            for key, value in keys.items():
                if key.endswith("_file") and value.strip():
                    out.append((section, key, value.strip()))
        return out

    def ai_fingerprint(self):
        """sha256 of the normalised [ai_services] section; guards ini drift between
        the two hosts. Passed in as HOOVER4_CONFIG_FINGERPRINT; ai services
        return it from /health and verify-stack.sh compares."""
        lines = []
        for key in sorted(self.values["ai_services"]):
            if key.endswith("_file"):
                continue  # host paths differ legitimately between the two boxes
            lines.append("%s=%s" % (key, self.values["ai_services"][key].strip()))
        return hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()[:16]

    def active_llm_provider(self):
        """The provider main_services should talk to: selfhosted when the local vLLM
        is on, otherwise the first enabled cloud provider, else None."""
        if self.get_bool("ai_services", "llm_selfhosted") and \
                self.get_bool("llm_provider.selfhosted", "enabled"):
            return "selfhosted"
        for section in LLM_PROVIDER_SECTIONS:
            name = section.split(".", 1)[1]
            if name != "selfhosted" and self.get_bool(section, "enabled"):
                return name
        return None

    def llm_base_url(self, provider):
        if provider == "selfhosted" and not self.get("llm_provider.selfhosted", "base_url"):
            return "http://%s:%s/v1" % (
                self.get("ai_services", "host"), self.get("ai_services", "vllm_port"))
        return self.get("llm_provider." + provider, "base_url")

    def llm_model(self, provider):
        model = self.get("llm_provider." + provider, "model")
        if not model and provider == "selfhosted":
            model = self.get("ai_services", "vllm_served_name")
        return model

    def llm_api_key_file(self, provider):
        if provider == "selfhosted" and not self.get("llm_provider.selfhosted", "api_key_file"):
            return self.get("ai_services", "vllm_api_key_file")
        return self.get("llm_provider." + provider, "api_key_file")


# --------------------------------------------------------------------------------------
# Rendering: ini -> .env
# --------------------------------------------------------------------------------------

#: Seconds the container runtime waits beyond the worker's own graceful period.
#:
#: The worker spends its graceful period letting in-flight activities finish, and only
#: then cancels the ones still running. Those cancellations still have to unwind, and if
#: SIGKILL arrives at that moment the graceful period bought nothing. This margin is
#: what the unwinding gets.
WORKER_SHUTDOWN_MARGIN_SECONDS = 30


def worker_graceful_shutdown_seconds(cfg):
    """The worker's graceful shutdown period, in whole seconds."""
    raw = cfg.get("main_services", "worker_graceful_shutdown_seconds")
    try:
        value = int(raw)
    except ValueError:
        fail("[main_services] worker_graceful_shutdown_seconds is not a number: %r" % raw)
    if value < 0:
        fail("[main_services] worker_graceful_shutdown_seconds must not be negative")
    return value


def render_main_env(cfg):
    """Env vars for main_services/ops/docker/.env. Ports come from the ini; no port
    literal appears here except the website's 12345 (which is not rendered at all — it
    stays in the compose file where humans read it)."""
    m = "main_services"
    env = {}
    env["COMPOSE_PROJECT_NAME"] = "hoover4"
    env["TZ"] = "UTC"
    env["HOOVER4_REPO_ROOT"] = str(REPO_ROOT)
    env["HOOVER4_CONFIG_FINGERPRINT"] = cfg.ai_fingerprint()

    for key in DEFAULTS[m]:
        if key.endswith("_port") and key != "website_port":
            env[key.upper()] = cfg.get(m, key)
    env["SERENA_PORT"] = cfg.get(m, "serena_port")

    for key in ("cassandra_version", "elasticsearch_version", "temporal_version",
                "temporal_ui_version", "garage_version", "garage_image_digest",
                "garage_capacity"):
        env[key.upper()] = cfg.get(m, key)

    # Read by auto-setup's config template as `persistence.numHistoryShards`.
    env["NUM_HISTORY_SHARDS"] = cfg.get(m, "temporal_history_shards")

    # Endpoints derived from the provider choices.
    ai_host = container_reachable_host(cfg.get("ai_services", "host"))
    ner_provider = cfg.get(m, "ner_provider")
    spacy_twin = "http://hoover4-ner-spacy:8000/v1"   # CPU twin, same network
    if ner_provider in ("gpu", "both"):
        env["NER_URL"] = "http://%s:%s/v1" % (ai_host, cfg.get("ai_services", "ai_server_port"))
    elif ner_provider == "spacy":
        env["NER_URL"] = spacy_twin
    else:
        env["NER_URL"] = ""

    # Where GPU_FALLBACK actually falls back to. tasks/remote.py walks the
    # endpoint list in order and skips empty entries, so this stays empty when the
    # twin is not running -- and an unreachable GPU then fails fast, naming the
    # url, instead of stalling. Never point the fallback at the primary.
    env["NER_URL_FALLBACK"] = (
        spacy_twin
        if ner_provider in ("gpu", "both") and cfg.get(m, "gpu_fallback") == "true"
        and _ner_spacy_twin_enabled(cfg)
        else ""
    )

    # The OCR tier, one endpoint per engine.
    #
    # Unlike NER there is no fallback between them: the engine is part of the storage key
    # (`ocr_easyocr_en` vs `ocr_tesseract_eng`), so serving an EasyOCR request from
    # Tesseract would file Tesseract's text under EasyOCR's name -- and Tesseract has
    # already run as its own variant, so the two would be identical rows under different
    # labels. An engine with no endpoint simply produces no variant.
    env["OCR_TESSERACT_URL"] = (
        # Same network, so the container name and its internal port -- never the
        # published one. The published port exists for humans and verify-stack.
        "http://hoover4-tesseract-cpu:8000/ocr"
        if cfg.get(m, "tesseract_cpu_enabled") == "true"
        else ""
    )
    env["OCR_EASYOCR_URL"] = (
        "http://%s:%s/ocr" % (ai_host, cfg.get("ai_services", "easyocr_port"))
        if cfg.get("ai_services", "easyocr_enabled") == "true"
        else ""
    )

    # The regex entity scanner. Always running, so this is never empty and the scan stage
    # never has to branch on its absence. Same network, container name and internal port
    # — the published port exists for humans and for verify-stack. Both the worker (which
    # scans) and the website (which proxies the explainer) read it.
    env["REGEX_SCANNER_URL"] = "http://hoover4-regex-entity-scanner:19705"
    env["REGEX_ENTITY_SCANNER_PORT"] = cfg.get(m, "regex_entity_scanner_port")
    env["REGEX_SCANNER_THREADS"] = cfg.get(m, "regex_scanner_threads")
    env["REGEX_SCANNER_QUEUE_DEPTH"] = cfg.get(m, "regex_scanner_queue_depth")

    # The searchable-PDF assembler. It has no engine of its own -- it renders pages and
    # calls the two endpoints above -- so it is enabled independently of them, and empty
    # here means the pipeline produces no OCR'd-PDF variants at all.
    env["OCR_PDF_URL"] = (
        "http://hoover4-ocr-pdf:8000/ocr-pdf"
        if cfg.get(m, "ocr_pdf_enabled") == "true"
        else ""
    )

    # The embeddings endpoint (P5 chunk+embed calls it; the same server also serves
    # /v1/rerank, so one base URL covers both). No CPU twin exists yet —
    # embeddings_cpu_port is reserved but nothing serves it, so "cpu" renders empty and
    # the embed activity will fail fast naming the setting rather than hang.
    emb_provider = cfg.get(m, "embeddings_provider")
    if emb_provider == "gpu":
        env["EMBEDDINGS_URL"] = "http://%s:%s/v1" % (
            ai_host, cfg.get("ai_services", "ai_server_port"))
    else:
        env["EMBEDDINGS_URL"] = ""
    env["RERANK_URL"] = (
        env["EMBEDDINGS_URL"]
        if env["EMBEDDINGS_URL"] and cfg.get("ai_services", "reranker_enabled") == "true"
        else ""
    )

    provider = cfg.active_llm_provider()
    if provider is not None:
        env["LLM_BASE_URL"] = cfg.llm_base_url(provider)
        env["LLM_MODEL"] = cfg.llm_model(provider)
        key_file = cfg.llm_api_key_file(provider)
        if key_file:
            # Bind-mount source only; the container reads /run/secrets/llm_api_key.
            env["LLM_API_KEY_FILE_HOST"] = key_file
    else:
        env["LLM_BASE_URL"] = ""
        env["LLM_MODEL"] = ""

    env["TEMPORAL_UI_URL"] = "http://localhost:%s" % cfg.get(m, "temporal_ui_port")
    env["EXTERNAL_CLICKHOUSE_URL"] = "http://localhost:%s" % cfg.get(m, "clickhouse_http_port")
    env["HOOVER4_DEMO_MODE"] = cfg.get(m, "demo_mode")
    # The address half of every published port mapping. The website's own port stays
    # hardcoded at 12345 in the compose file (see MAIN_PUBLISHED) -- only the interface
    # it answers on is configurable, which is the half that decides who can reach it.
    env["WEBSITE_BIND_IP"] = cfg.get(m, "website_bind_ip")
    env["INFRA_BIND_IP"] = cfg.get(m, "infra_bind_ip")
    # Read by the website (the creation form lists its subfolders) and by the worker
    # (the ingest walker gets the resulting absolute path). Both containers mount the
    # same host directory there, so the one value is meaningful on both sides.
    env["DATASETS_MOUNT_PATH"] = cfg.get(m, "datasets_mount_path")
    if cfg.get(m, "testdata_dir"):
        env["HOOVER4_TESTDATA_DIR"] = cfg.get(m, "testdata_dir")
    if cfg.get(m, "mcp_shared_secret_file"):
        env["MCP_SHARED_SECRET_FILE_HOST"] = cfg.get(m, "mcp_shared_secret_file")
    # Rendered only when set: the website reads its own default when the variable is
    # absent, and an empty value would parse as "0" on some paths and as garbage on
    # others.
    if cfg.get(m, "search_max_parallelism"):
        env["HOOVER4_SEARCH_MAX_PARALLELISM"] = cfg.get(m, "search_max_parallelism")
    if cfg.get(m, "search_timeout_seconds"):
        env["HOOVER4_SEARCH_TIMEOUT_SECONDS"] = cfg.get(m, "search_timeout_seconds")

    # Pipeline switches, rendered unconditionally so the worker can pick up a new one
    # without a deploy.py change.
    for key in ("ner_provider", "embeddings_provider",
                "pdf_ocr_provider", "tesseract_languages", "gpu_fallback",
                "gpu_connect_timeout_ms", "gpu_circuit_break_seconds"):
        env[key.upper()] = cfg.get(m, key)

    # The two language settings are the stack-wide DEFAULTS a dataset inherits until the
    # admin page writes a `dataset_settings` row for it, after which that row wins.
    # EasyOCR's lives in the
    # [ai_services] section because that is where its server is configured, but the
    # worker is what needs it -- it decides how many passes to run.
    env["EASYOCR_LANGUAGES"] = cfg.get("ai_services", "easyocr_languages")

    # Worker fleet sizing. Rendered only when set: an empty value would reach the worker
    # as the string "" and every tier has a default it is better off keeping.
    # Rendered only when set: the compose file carries the same default, and an empty
    # value there would reach podman as a memory limit of "".
    if cfg.get(m, "worker_mem_limit"):
        env["HOOVER4_WORKER_MEM_LIMIT"] = cfg.get(m, "worker_mem_limit")
    if cfg.get(m, "common_workers"):
        env["HOOVER4_COMMON_WORKERS"] = cfg.get(m, "common_workers")
    for tier in ("common", "tika", "ocr", "nlp", "embed", "indexing"):
        value = cfg.get(m, "%s_concurrency" % tier)
        if value:
            env["HOOVER4_%s_CONCURRENCY" % tier.upper()] = value

    # Graceful shutdown, rendered twice from ONE ini key. The first value is what the
    # Temporal worker gives its in-flight activities before cancelling them; the second
    # is how long the container runtime waits after SIGTERM before SIGKILL. The runtime
    # wins, so its number must be the larger one -- the margin is what the cancelled
    # activities get to unwind, close their files and record what they finished. Keeping
    # the two in one place is the point: split across the ini and the compose file they
    # drift, and the setting silently stops being true.
    graceful = worker_graceful_shutdown_seconds(cfg)
    env["HOOVER4_WORKER_GRACEFUL_SHUTDOWN_SECONDS"] = str(graceful)
    env["HOOVER4_WORKER_STOP_GRACE_PERIOD"] = "%ds" % (
        graceful + WORKER_SHUTDOWN_MARGIN_SECONDS)

    return env


def render_ai_env(cfg):
    a = "ai_services"
    env = {}
    env["COMPOSE_PROJECT_NAME"] = "ai_services"
    env["TZ"] = "UTC"
    env["HOOVER4_REPO_ROOT"] = str(REPO_ROOT)
    env["HOOVER4_CONFIG_FINGERPRINT"] = cfg.ai_fingerprint()
    env["AI_BIND_IP"] = cfg.get(a, "bind_ip")

    for key in ("vllm_port", "ai_server_port", "easyocr_port"):
        env[key.upper()] = cfg.get(a, key)

    env["VLLM_IMAGE"] = cfg.get(a, "vllm_image")
    env["LLM_MODEL_NAME"] = cfg.get(a, "vllm_model")
    env["LLM_SERVED_NAME"] = cfg.get(a, "vllm_served_name")
    env["VLLM_GPU_FRACTION"] = cfg.get(a, "vllm_gpu_fraction")
    env["VLLM_MAX_MODEL_LEN"] = cfg.get(a, "vllm_max_model_len")
    env["VLLM_MAX_NUM_SEQS"] = cfg.get(a, "vllm_max_num_seqs")
    env["VLLM_TOOL_PARSER"] = cfg.get(a, "vllm_tool_parser")
    env["VLLM_REASONING_PARSER"] = cfg.get(a, "vllm_reasoning_parser")
    if cfg.get(a, "vllm_api_key_file"):
        env["VLLM_API_KEY_FILE_HOST"] = cfg.get(a, "vllm_api_key_file")
    if cfg.get(a, "hf_token_file"):
        env["HF_TOKEN_FILE_HOST"] = cfg.get(a, "hf_token_file")

    env["AI_SERVER_ENABLE_HALF_PRECISION"] = cfg.get(a, "half_precision")
    env["AI_SERVER_ENABLE_TORCH_COMPILE"] = cfg.get(a, "torch_compile")
    env["AI_SERVER_ENABLE_NER"] = cfg.get(a, "ner_enabled")
    env["AI_SERVER_ENABLE_EMBEDDINGS"] = cfg.get(a, "embeddings_enabled")
    env["AI_SERVER_ENABLE_RERANKER"] = cfg.get(a, "reranker_enabled")
    env["AI_SERVER_NER_CONCURRENCY"] = cfg.get(a, "ai_server_ner_concurrency")
    env["AI_SERVER_EMBED_CONCURRENCY"] = cfg.get(a, "ai_server_embed_concurrency")
    env["AI_SERVER_RERANK_CONCURRENCY"] = cfg.get(a, "ai_server_rerank_concurrency")
    env["EMBEDDINGS_MODEL"] = cfg.get(a, "embeddings_model")
    env["EMBEDDINGS_DIM"] = cfg.get(a, "embeddings_dim")
    env["RERANKER_MODEL"] = cfg.get(a, "reranker_model")
    env["EASYOCR_LANGUAGES"] = cfg.get(a, "easyocr_languages")
    return env


def write_env_file(path, env):
    lines = [ENV_HEADER]
    for key in sorted(env):
        lines.append("%s=%s" % (key, env[key]))
    content = "\n".join(lines) + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


# --------------------------------------------------------------------------------------
# Compose invocation assembly
# --------------------------------------------------------------------------------------

def _ner_spacy_twin_enabled(cfg):
    """Whether the CPU NER twin will actually be running.

    One config key, which is also what selects the overlay that defines the service, so
    "enabled" and "running" cannot drift apart. This used to grep the base compose file
    for the string `hoover4-ner-spacy`, which was true whenever the string appeared
    anywhere in it -- in a comment, in a volume name, in another service's depends_on --
    and so was true unconditionally.

    Announcing a fallback url for a container that does not exist is worse than having
    none: tasks/remote.py would spend a connect timeout on it before failing, on every
    single batch.
    """
    return cfg.get_bool("main_services", "ner_spacy_enabled")


def selected_overlays(cfg, side):
    overlays = []
    if side == "ai":
        base = AI_OVERLAYS
    else:
        base = MAIN_OVERLAYS
    for flag, rel, _svc in base:
        if flag is None or cfg.get_bool("ai_services" if side == "ai" else "main_services", flag):
            overlays.append(rel)
    return overlays


def compose_files(cfg, side):
    if side == "ai":
        files = [str(AI_COMPOSE_DIR / "docker-compose.yaml")]
        files += [str(AI_COMPOSE_DIR / rel) for rel in selected_overlays(cfg, "ai")]
    else:
        files = [str(MAIN_COMPOSE_DIR / "docker-compose.yaml")]
        files += [str(MAIN_COMPOSE_DIR / rel) for rel in selected_overlays(cfg, "main")]
    for f in files:
        if not Path(f).exists():
            fail("compose file missing: %s" % f)
    return files


def compose_command(cfg, side, runtime, extra_args):
    cmd = runtime.compose_prefix()
    for f in compose_files(cfg, side):
        cmd += ["-f", f]
    cmd += extra_args
    return cmd


def project_name(side):
    return "ai_services" if side == "ai" else "hoover4"


class Runtime:
    """Container runtime detection. This repo runs on podman with the docker shim and
    podman-compose as the compose provider; plain docker is supported too."""

    def __init__(self):
        self.docker = shutil.which("docker")
        self.podman = shutil.which("podman")
        if not self.docker and not self.podman:
            fail("no container runtime found: looked for 'docker' and 'podman' on PATH")
        self.name = "podman" if self.podman else "docker"
        self.engine = self.podman or self.docker

    def compose_prefix(self):
        # Both docker (shim) and podman delegate `compose` to the installed provider
        # (podman-compose / docker-compose plugin).
        return [self.docker or self.podman, "compose"]

    def describe(self):
        return self.name

    def run(self, args, **kwargs):
        return subprocess.run([self.engine] + args, **kwargs)


# --------------------------------------------------------------------------------------
# Preflights — all run before any `docker compose` invocation, in this order
# --------------------------------------------------------------------------------------

def preflight_os():
    if not sys.platform.startswith("linux"):
        fail("only Linux is supported (got %s)" % sys.platform)


def preflight_runtime(rt):
    print("preflight: container runtime: %s (%s)" % (rt.describe(), rt.engine))


def preflight_gpu(cfg, side):
    """GPU overlays requested -> nvidia-smi must work, and on podman a CDI spec must
    exist. Refuses before compose runs, so a missing CDI never surfaces as an
    unfriendly OCI mount error at container start."""
    if side != "ai":
        return
    requested = [rel for rel in selected_overlays(cfg, "ai") if rel in AI_GPU_OVERLAYS]
    if not requested:
        return
    smi = shutil.which("nvidia-smi")
    if not smi or subprocess.run([smi], stdout=subprocess.DEVNULL,
                                 stderr=subprocess.DEVNULL).returncode != 0:
        fail("nvidia-smi failed (no usable NVIDIA GPU), but GPU overlays were "
             "requested: %s" % ", ".join(requested))
    cdi_ok = os.path.exists(CDI_SPEC)
    if not cdi_ok and shutil.which("nvidia-ctk"):
        cdi_ok = subprocess.run(
            ["nvidia-ctk", "cdi", "list"], stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL).returncode == 0
    if not cdi_ok:
        fail("GPU overlays requested (%s) but no NVIDIA CDI spec found at %s.\n"
             "Generate it with:\n"
             "    sudo nvidia-ctk cdi generate --output=%s"
             % (", ".join(requested), CDI_SPEC, CDI_SPEC))


def preflight_cdi_prune(rt):
    """Fold of ai_services/start-docker.sh: drop CDI mounts whose host path does not
    exist — a partial driver upgrade leaves entries pointing at files that were never
    installed, and crun refuses to start the GPU containers over a missing bind
    source. Host-A (ai_services) preflight."""
    if not os.path.isfile(CDI_SPEC) or not os.access(CDI_SPEC, os.R_OK):
        print("preflight: no readable CDI spec at %s — skipping prune" % CDI_SPEC)
        return
    with open(CDI_SPEC, "r", encoding="utf-8") as fh:
        lines = fh.readlines()
    stale = []
    for line in lines:
        match = re.match(r"^\s*-?\s*hostPath:\s*(\S+)\s*$", line)
        if match and not os.path.exists(match.group(1)):
            stale.append(match.group(1))
    if not stale:
        print("preflight: CDI spec ok — every mount resolves")
        return
    for path in stale:
        print("preflight: CDI spec references missing file: %s" % path)
    # Remove the whole list item (hostPath + its containerPath/options lines).
    pruned = []
    skip_block = False
    for i, line in enumerate(lines):
        item = re.match(r"^(\s*)-\s*hostPath:\s*(\S+)\s*$", line)
        if item:
            skip_block = item.group(2) in stale
        elif skip_block and re.match(r"^\S", line):
            skip_block = False
        elif skip_block and re.match(r"^\s+-\s+hostPath:", line):
            skip_block = False
            pruned.append(line)
            continue
        if not skip_block:
            pruned.append(line)
    if shutil.which("sudo") and subprocess.run(
            ["sudo", "-n", "true"], stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL).returncode == 0:
        backup = "%s.bak-deploy" % CDI_SPEC
        subprocess.run(["sudo", "cp", "-a", CDI_SPEC, backup], check=True)
        import tempfile
        with tempfile.NamedTemporaryFile("w", delete=False) as tmp:
            tmp.writelines(pruned)
            tmp_path = tmp.name
        subprocess.run(["sudo", "cp", tmp_path, CDI_SPEC], check=True)
        subprocess.run(["sudo", "chmod", "644", CDI_SPEC], check=True)
        os.unlink(tmp_path)
        print("preflight: CDI spec patched (previous at %s)" % backup)
    else:
        print("preflight: WARNING: %s needs root to fix and sudo is not available; "
              "GPU services may fail with an OCI runtime error" % CDI_SPEC)


def preflight_secrets(cfg):
    repo = str(REPO_ROOT)
    for section, key, path in cfg.secret_files():
        if not os.path.exists(path):
            fail("[%s] %s: secret file is missing: %s" % (section, key, path))
        mode = stat.S_IMODE(os.stat(path).st_mode)
        if mode & (stat.S_IRWXG | stat.S_IRWXO):
            fail("[%s] %s: secret file %s is group/world accessible (mode %04o); "
                 "chmod 600 it" % (section, key, path, mode))
        real = os.path.realpath(path)
        if real == repo or real.startswith(repo + os.sep):
            fail("[%s] %s: secret file %s is inside the repository checkout — keys "
                 "inside the checkout leak into build contexts and commits"
                 % (section, key, path))


def local_ip_addresses():
    """Every IPv4 address configured on this machine, plus loopback."""
    addrs = {"127.0.0.1", "localhost", "0.0.0.0"}
    try:
        out = subprocess.run(["ip", "-4", "-o", "addr"], capture_output=True,
                             text=True).stdout
        addrs.update(re.findall(r"inet (\d+\.\d+\.\d+\.\d+)", out))
    except OSError:
        pass
    return addrs


def container_reachable_host(host):
    """Rewrite an ai_services host that is *this* machine into a name containers
    can actually route to.

    ai_services lives on its own private network and main_services reaches it
    over the published ports on `[ai_services] host`. That
    works when the GPU tier is a different box. When both tiers share one box — the
    dev setup — the ini names this host's own LAN IP, and a rootless podman container
    cannot route to its host's LAN address: the connect hangs until the OS gives up,
    which surfaces as an NER activity stalling for minutes with zero CPU load.

    Podman (and Docker Desktop) inject `host.containers.internal` into every
    container's /etc/hosts pointing at the host gateway, which is routable. Remote
    hosts are returned unchanged — they are reachable from the container as-is.
    """
    if host in local_ip_addresses():
        return "host.containers.internal"
    return host


def port_is_free(port, bind_ips):
    for ip in bind_ips:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            sock.bind((ip, port))
        except OSError:
            return False
        finally:
            sock.close()
    return True


def project_published_ports(rt, side):
    """Host ports already published by THIS compose project's own containers — a
    redeploy must not fail its own port preflight on the running stack."""
    filters = ["label=com.docker.compose.project=%s" % project_name(side)]
    if side == "main":
        # Serena is its own project (hoover4-devtools) but is deployed by this side.
        filters.append("name=^hoover4-serena$")
    ports = set()
    for flt in filters:
        result = rt.run(["ps", "--filter", flt, "--format", "{{.Ports}}"],
                        capture_output=True, text=True)
        for token in result.stdout.replace("\n", " ").split():
            # tokens look like 0.0.0.0:21900->8123/tcp or 21900->8123/tcp
            match = re.match(r"(?:[\d.]+:)?(\d+)->", token)
            if match:
                ports.add(int(match.group(1)))
    return ports


def expected_ports(cfg, side):
    """[(service, port)] this side publishes with the current ini. Shared by the port
    preflight and the post-`down` wait so the two can never disagree."""
    if side == "ai":
        entries = []
        for flag, rel, svc in AI_OVERLAYS:
            if rel in selected_overlays(cfg, "ai"):
                entries.append((svc, "ai_services", flag.replace("_enabled", "_port")
                                if flag != "llm_selfhosted" else "vllm_port"))
        return [(svc, int(cfg.get(sec, key))) for svc, sec, key in entries]
    checks = [(svc, int(key) if sec is None else int(cfg.get(sec, key)))
              for svc, sec, key in MAIN_PUBLISHED]
    if cfg.get_bool("main_services", "serena_enabled"):
        checks.append(("hoover4-serena", int(cfg.get("main_services", "serena_port"))))
    return checks


def preflight_ports(cfg, side, rt):
    own = project_published_ports(rt, side)
    taken = []
    checks = expected_ports(cfg, side)
    if side == "ai":
        bind_ips = [cfg.get("ai_services", "bind_ip")]
    else:
        # Services bind either loopback or all interfaces; a port is unusable if
        # either fails.
        bind_ips = ["127.0.0.1", "0.0.0.0"]
    for svc, port in checks:
        if port in own:
            continue  # already published by this project's own running container
        if not port_is_free(port, bind_ips):
            taken.append((svc, port))
    if taken:
        detail = "\n".join("    port %d wanted by %s" % (p, s) for s, p in taken)
        fail("ports already in use:\n%s" % detail)


def preflight_ner_spacy(cfg, side):
    """A knob that is rendered and not read is the failure mode to refuse, not degrade.

    `ner_provider = spacy` with `ner_spacy_enabled = false` asks for entities from a
    service that will not be running. Silently producing no entities at all would look
    exactly like a corpus with none in it.
    """
    if side == "ai":
        return
    if cfg.get("main_services", "ner_provider") != "spacy":
        return
    if not cfg.get_bool("main_services", "ner_spacy_enabled"):
        fail("[main_services] ner_provider = spacy but ner_spacy_enabled = false — the "
             "spaCy twin would not be running, so no entities would be extracted at "
             "all. Set ner_spacy_enabled = true, or pick another ner_provider.")


def preflight_ai_enabled(cfg, side):
    if side == "ai" and not cfg.get_bool("ai_services", "enabled"):
        fail("--ai-services was requested but [ai_services] says enabled = false — "
             "the ini has this tier off")


def preflight_compose_yaml(cfg, side):
    """Strict-parse the compose files this side will use, before anything is built.

    podman-compose accepts YAML that Docker Compose rejects -- a duplicate mapping key
    is the one that has actually happened here, from an edit that removed a service's
    name line and left its `driver:` line behind to attach to the service above. That
    file deploys fine on a podman host and fails on a Docker host with
    `mapping key "driver" already defined`, which is a bad way to find out.

    PyYAML's own `safe_load` is NOT strict enough on its own -- it accepts a duplicate
    key and lets the last one win, which is exactly the case that has to be caught here,
    so the loader below rejects duplicates explicitly.

    Skipped when PyYAML is absent: this is a guard rail, not a dependency worth adding
    to a script whose whole job is to run before anything is installed.
    """
    try:
        import yaml
    except ImportError:
        return

    class _StrictLoader(yaml.SafeLoader):
        pass

    def _reject_duplicates(loader, node, deep=False):
        seen = {}
        for key_node, value_node in node.value:
            key = loader.construct_object(key_node, deep=deep)
            if key in seen:
                raise yaml.YAMLError(
                    'duplicate mapping key "%s" on line %d (first seen on line %d)'
                    % (key, key_node.start_mark.line + 1, seen[key] + 1))
            seen[key] = key_node.start_mark.line
        return {loader.construct_object(k, deep=deep): loader.construct_object(v, deep=deep)
                for k, v in node.value}

    _StrictLoader.add_constructor(
        yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _reject_duplicates)

    for path in compose_files(cfg, side):
        try:
            with open(path, "r", encoding="utf-8") as fh:
                yaml.load(fh, Loader=_StrictLoader)
        except yaml.YAMLError as exc:
            fail("%s is not valid compose YAML:\n    %s"
                 % (path, str(exc).replace("\n", "\n    ")))


def temporal_shard_count_in_store(rt):
    """The shard count the Temporal persistence store was initialised with, or None.

    The live server is asked first because it is authoritative and cheap. With the
    server down, Cassandra still knows: shard-info rows are `type = 0` in
    `temporal.executions` and their ids run 1..N. Returns None when neither is
    reachable, which is the ordinary state of a stack that has never been started.
    """
    describe = rt.run(["exec", "temporal", "temporal", "operator", "cluster",
                       "describe", "--address", "temporal:7233", "-o", "json"],
                      capture_output=True, text=True)
    if describe.returncode == 0:
        try:
            count = int(json.loads(describe.stdout).get("historyShardCount", 0))
        except (ValueError, TypeError, json.JSONDecodeError):
            count = 0
        if count > 0:
            return count
    cql = rt.run(["exec", "temporal-cassandra", "cqlsh", "-u", "cassandra",
                  "-p", "cassandra", "-e",
                  "SELECT shard_id FROM temporal.executions WHERE type=0 ALLOW FILTERING;"],
                 capture_output=True, text=True)
    if cql.returncode != 0:
        return None
    ids = [int(tok) for tok in cql.stdout.split() if tok.isdigit()]
    return max(ids) if ids else None


def preflight_temporal_shards(cfg, side, rt):
    """Refuse to start against a store initialised with a different shard count.

    `numHistoryShards` is immutable for the life of the persistence store: the server
    will not open a keyspace that was set up with another value. Left to itself it dies
    with a Cassandra error that names neither number, so catch it here and say what the
    two values are and how to reconcile them.
    """
    if side != "main":
        return
    want = cfg.get("main_services", "temporal_history_shards")
    try:
        want = int(want)
    except ValueError:
        fail("[main_services] temporal_history_shards is not a number: %r" % want)
    if want < 1:
        fail("[main_services] temporal_history_shards must be at least 1")
    have = temporal_shard_count_in_store(rt)
    if have is None or have == want:
        return
    fail("Temporal's store is initialised with %d history shards but hoover4.ini asks "
         "for %d. The count is fixed for the life of the store, so the server would "
         "refuse to start.\n"
         "    ./deploy --reset-temporal    drop Temporal's history and re-initialise "
         "at %d (leaves ClickHouse, Garage and Manticore alone)\n"
         "    set temporal_history_shards = %d in hoover4.ini to keep the store as it is"
         % (have, want, want, have))


def run_preflights(cfg, side, rt, starting):
    preflight_os()
    preflight_runtime(rt)
    if starting:
        preflight_gpu(cfg, side)
        if side == "ai":
            preflight_cdi_prune(rt)
    preflight_secrets(cfg)
    if starting:
        preflight_ports(cfg, side, rt)
    preflight_ai_enabled(cfg, side)
    preflight_ner_spacy(cfg, side)
    preflight_compose_yaml(cfg, side)
    if starting:
        preflight_temporal_shards(cfg, side, rt)


# --------------------------------------------------------------------------------------
# Network: ai_services gets its own private network
# --------------------------------------------------------------------------------------

def _host_resolvers():
    """Upstream resolvers from the host's resolv.conf, skipping 127.* stubs.

    A 127.* nameserver (systemd-resolved's 127.0.0.53) is a host-local stub; a
    container cannot reach it, and aardvark-dns forwarding to it is the flaky
    configuration that wedges external DNS for the whole stack while leaving
    container-name resolution working, so the breakage looks like an app bug.
    """
    resolvers = []
    try:
        with open("/etc/resolv.conf", "r", encoding="utf-8") as fh:
            for line in fh:
                parts = line.split()
                if len(parts) == 2 and parts[0] == "nameserver" \
                        and not parts[1].startswith("127."):
                    resolvers.append(parts[1])
    except OSError:
        pass
    return resolvers


def ensure_network(rt, name):
    """Create the network if missing, with explicit DNS resolvers attached.

    Fresh podman networks have no upstream DNS until resolvers are attached, so
    create with settings from the host's resolv.conf, falling back to public
    resolvers when the host only has a local stub.

    An existing network is also checked: podman cannot change resolvers on a
    live network, so one without them (e.g. created by compose before this
    check existed) is removed and recreated — possible only when nothing is
    attached, i.e. right after a `--reset`. With containers attached we warn
    and keep the network as-is."""
    resolvers = _host_resolvers()
    if rt.name == "podman" and not resolvers:
        resolvers = ["1.1.1.1", "8.8.8.8"]
    existing = rt.run(["network", "inspect", name],
                      capture_output=True, text=True)
    if existing.returncode == 0:
        if rt.name != "podman":
            return
        try:
            info = json.loads(existing.stdout)[0]
        except (ValueError, IndexError):
            return
        if info.get("network_dns_servers"):
            return
        if info.get("containers"):
            print("WARNING: network %s has no DNS resolvers and containers are "
                  "attached; run ./deploy --reset to recreate it with DNS "
                  "(external lookups from containers will be flaky until then)"
                  % name)
            return
        print("network %s exists without DNS resolvers — recreating (dns: %s)"
              % (name, ", ".join(resolvers)))
        rm = rt.run(["network", "rm", name], capture_output=True, text=True)
        if rm.returncode != 0:
            fail("could not remove DNS-less network %s: %s"
                 % (name, rm.stderr.strip()))
    args = ["network", "create"]
    if rt.name == "podman":
        for resolver in resolvers[:3]:
            args += ["--dns", resolver]
    # docker compose adopts a network it did not create only when that network carries
    # the labels compose would have set itself; without them it refuses the whole `up`
    # with "network ... has incorrect label com.docker.compose.network". podman-compose
    # does not check, which is why creating the network here was invisible until a
    # deploy on plain docker. On both sides the compose network KEY, its `name:` and
    # the project name are the same string, so one value fills all three labels.
    args += ["--label", "com.docker.compose.project=%s" % name,
             "--label", "com.docker.compose.network=%s" % name]
    print("creating network %s (dns: %s)" % (name, ", ".join(resolvers) or "default"))
    result = rt.run(args + [name], capture_output=True, text=True)
    if result.returncode != 0:
        fail("could not create network %s: %s" % (name, result.stderr.strip()))


def verify_network_dns(rt, cfg, side):
    """Verify name resolution between two containers of the stack before declaring
    success — a fresh podman network without resolvers is the failure this catches."""
    result = rt.run(["ps", "--filter", "label=com.docker.compose.project=%s"
                     % project_name(side), "--format", "{{.Names}}"],
                    capture_output=True, text=True)
    names = [n for n in result.stdout.split() if n]
    if len(names) < 2:
        return
    first, second = names[0], names[1]
    check = rt.run(["exec", first, "python", "-c",
                    "import socket; print(socket.gethostbyname('%s'))" % second],
                   capture_output=True, text=True)
    if check.returncode != 0:
        check = rt.run(["exec", first, "getent", "hosts", second],
                       capture_output=True, text=True)
    if check.returncode != 0:
        fail("containers on the %s network cannot resolve each other "
             "(%s -> %s failed) — fresh podman networks need resolvers attached"
             % (project_name(side), first, second))
    print("network %s: %s resolves %s" % (project_name(side), first, second))


# --------------------------------------------------------------------------------------
# up / build / down / reset
# --------------------------------------------------------------------------------------

def compose_up(cfg, side, rt, build):
    files = compose_files(cfg, side)
    if build:
        build_cmd = rt.compose_prefix()
        for f in files:
            build_cmd += ["-f", f]
        # `up -d` after a rebuild keeps the old image; build and force-recreate.
        run_or_fail(build_cmd + ["build"])
        up_args = ["up", "-d", "--force-recreate"]
    else:
        up_args = ["up", "-d"]
    run_or_fail(compose_command(cfg, side, rt, up_args))
    if rt.name == "podman" and build:
        podman_stale_image_fix(cfg, side, rt, files)
    if side == "main":
        report_worker_stop_timeout(cfg, rt)


def report_worker_stop_timeout(cfg, rt):
    """Say out loud whether the worker's graceful shutdown period is actually reachable.

    `stop_grace_period` in the compose file is not the whole story under podman, and the
    difference is invisible unless something says so -- which is the entire reason this
    prints rather than staying silent on the happy path.

    podman-compose applies the grace period only when IT stops the container: it passes
    `-t <seconds>` to `podman stop` on down/stop/restart. It does NOT write the value into
    the container, and `podman update` cannot set it afterwards -- `--stop-timeout` is
    accepted only at creation. So the container keeps podman's own default of 10 seconds,
    and anything that stops it directly (`docker stop`, `docker restart`, a supervisor,
    a person) kills through the graceful period at ten seconds no matter what the
    configuration says.

    A worker SIGKILLed part-way through draining is the exact failure the graceful period
    exists to prevent, so the number that is really in force is printed either way.
    """
    want = worker_graceful_shutdown_seconds(cfg) + WORKER_SHUTDOWN_MARGIN_SECONDS
    got = rt.run(["inspect", "hoover4-worker", "--format", "{{.Config.StopTimeout}}"],
                 capture_output=True, text=True)
    if got.returncode != 0:
        return
    raw = got.stdout.strip()
    try:
        effective = int(raw)
    except ValueError:
        return
    if effective >= want:
        print("preflight: worker stop grace period %ds, as configured" % effective)
        return
    print("preflight: WARNING: hoover4-worker was created with a %ds stop timeout, not "
          "the configured %ds — %s drops stop_grace_period at creation and cannot set it "
          "afterwards." % (effective, want, rt.describe()))
    print("preflight:          `./deploy --down` and `%s compose stop` still honour the "
          "full period; a direct `stop`/`restart` of this container does not, and must "
          "pass `-t %d` itself." % (rt.describe(), want))


def podman_stale_image_fix(cfg, side, rt, files):
    """podman-compose sometimes leaves the old container running the old image id even
    after --force-recreate. Detect that and fall back to `rm -f --depend` + up."""
    ps = rt.run(["ps", "--filter", "label=com.docker.compose.project=%s"
                 % project_name(side), "--format",
                 "{{.Names}} {{.Image}} {{.ImageID}}"], capture_output=True, text=True)
    stale = []
    for line in ps.stdout.splitlines():
        parts = line.split()
        if len(parts) < 3:
            continue
        name, image, running_id = parts[0], parts[1], parts[2]
        inspect = rt.run(["image", "inspect", image, "--format", "{{.Id}}"],
                         capture_output=True, text=True)
        latest = inspect.stdout.strip()
        if latest and running_id and latest != running_id:
            stale.append(name)
    if not stale:
        return
    print("podman kept old images running for: %s — recreating" % ", ".join(stale))
    rt.run(["rm", "-f", "--depend"] + stale)
    run_or_fail(compose_command(cfg, side, rt, ["up", "-d"]))


def reprobe_embeddings(rt):
    """Re-record what the GPU tier serves, after `--ai-services` brought it up.

    `server_settings.embeddings_serving_model` is the *truth* the whole vector half is
    built on, and bringing the AI tier up with a different `embeddings_model` is precisely
    when it goes stale. Every consumer then correctly refuses — which is the hard part to
    diagnose, because nothing is broken and nothing says so.

    Best effort, and never fatal to the deploy: the worker lives on the main stack, which
    may be on another host or simply not running. A model still loading is the normal
    case here, and the workers probe again at their own startup.
    """
    ps = rt.run(["ps", "--filter", "name=hoover4-worker", "--format", "{{.Names}}"],
                capture_output=True, text=True)
    if "hoover4-worker" not in (ps.stdout or ""):
        print("skipping the embeddings re-probe: hoover4-worker is not running here "
              "(run `./deploy` then `docker exec hoover4-worker uv run python main.py "
              "probe-embeddings` if the model changed)")
        return
    print("re-probing the embeddings endpoint...")
    result = rt.run(["exec", "hoover4-worker", "uv", "run", "python", "main.py",
                     "probe-embeddings"], capture_output=True, text=True)
    output = (result.stdout or "").strip() or (result.stderr or "").strip()
    if result.returncode != 0:
        print("WARNING: embeddings probe failed (%s); server_settings is unchanged and "
              "the embed/index stages will refuse until it succeeds" % output)
        return
    for line in output.splitlines():
        print("  %s" % line)


def serena_command(cfg, rt, extra_args):
    # --env-file is NOT optional here. Compose auto-discovers `.env` from the directory
    # of the first -f file; the main stack's first file is the base compose in
    # MAIN_COMPOSE_DIR, so it finds the generated .env, but the serena overlay lives in
    # MAIN_COMPOSE_DIR/compose/, which has none. Without this the overlay renders with
    # an empty ${HOOVER4_REPO_ROOT} and the repo bind mount fails with the singularly
    # unhelpful "Error: container directory cannot be empty".
    #
    # Do NOT add --project-directory: relative paths (the `../serena` build context)
    # resolve against the declaring file's own directory, which is already correct.
    cmd = rt.compose_prefix() + ["--env-file", str(MAIN_COMPOSE_DIR / ".env"),
                                 "-p", SERENA_PROJECT,
                                 "-f", str(MAIN_COMPOSE_DIR / SERENA_OVERLAY)]
    return cmd + extra_args


def compose_up_serena(cfg, rt, build):
    if not cfg.get_bool("main_services", "serena_enabled"):
        return
    if build:
        run_or_fail(serena_command(cfg, rt, ["build"]))
        run_or_fail(serena_command(cfg, rt, ["up", "-d", "--force-recreate"]))
    else:
        run_or_fail(serena_command(cfg, rt, ["up", "-d"]))


def wait_for_ports_released(cfg, side, rt, timeout_seconds=60):
    """Block until this project's published ports are actually free again.

    `compose down` returns as soon as the containers are gone, but on podman the
    project's pod publishes the ports on its infra container, and that teardown is
    asynchronous. So `./deploy --reset && ./deploy` would fail its own port preflight
    with a port it had just released ("port 12345 wanted by hoover4-website") — a race
    that looks exactly like a genuine conflict and sends you hunting for a process that
    does not exist. Wait it out here instead of making every caller rediscover it.
    """
    # Serena is a separate compose project that deliberately survives down/reset, so
    # its port is still held on purpose — waiting on it would burn the whole timeout
    # and print a warning about working as intended.
    wanted = [(svc, port) for svc, port in expected_ports(cfg, side)
              if svc != "hoover4-serena"]
    if not wanted:
        return
    bind_ips = ["0.0.0.0"]
    deadline = time.time() + timeout_seconds
    while True:
        busy = sorted(p for _, p in wanted if not port_is_free(p, bind_ips))
        if not busy:
            return
        if time.time() >= deadline:
            print("warning: ports still held %ds after down: %s"
                  % (timeout_seconds, ", ".join(str(p) for p in busy)), file=sys.stderr)
            return
        time.sleep(1)


def compose_down(cfg, side, rt):
    run_or_fail(compose_command(cfg, side, rt, ["down"]))
    wait_for_ports_released(cfg, side, rt)


def compose_reset(cfg, side, rt, reset_caches):
    """Scoped reset: only this compose project's containers and volumes. Model-cache
    volumes are preserved by name unless --reset-caches; the Serena container and its
    volume are never touched — killing it mid-session drops the MCP connection the
    agent is using to do the work. Serena survives by construction: it is a separate
    compose project (hoover4-devtools), so this project's `down` never selects it."""
    proj = project_name(side)
    run_or_fail(compose_command(cfg, side, rt, ["down"]))
    wait_for_ports_released(cfg, side, rt)
    volumes = rt.run(["volume", "ls", "--format", "{{.Name}}"],
                     capture_output=True, text=True).stdout.split()
    doomed = []
    for vol in volumes:
        if not vol.startswith(proj + "_"):
            continue
        if any(vol.endswith(sfx) for sfx in PROTECTED_VOLUME_SUFFIXES):
            continue
        if not reset_caches and any(vol.endswith(sfx) for sfx in CACHE_VOLUME_SUFFIXES):
            print("reset: preserving cache volume %s" % vol)
            continue
        doomed.append(vol)
    if doomed:
        run = rt.run(["volume", "rm", "-f"] + doomed, capture_output=True, text=True)
        if run.returncode != 0:
            fail("could not remove volumes: %s" % run.stderr.strip())
        for vol in doomed:
            print("reset: removed volume %s" % vol)


# Temporal's own persistence: the workflow history store and its visibility index.
# Scoped separately from --reset because the shard count can only change by dropping
# them, and there is no reason to lose the corpus to do it.
TEMPORAL_SERVICES = ["temporal-ui", "temporal", "temporal-cassandra",
                     "temporal-elasticsearch"]
TEMPORAL_VOLUME_SUFFIXES = ("temporal_cassandra", "temporal_elasticsearch")


def compose_reset_temporal(cfg, side, rt):
    """Drop Temporal's history and visibility stores, keeping every other volume.

    What is lost is workflow history, which retention already caps at 24 h with
    archival off. What is kept is everything the corpus lives in -- ClickHouse, Garage,
    Manticore, Redis. Running ingests do not survive: their workflows are gone, and
    P0 re-scans a dataset from disk on the next run.
    """
    if side != "main":
        fail("--reset-temporal applies to the main stack; drop --ai-services")
    proj = project_name(side)
    run_or_fail(compose_command(cfg, side, rt, ["stop"] + TEMPORAL_SERVICES))
    # Removal goes through the runtime, not compose: podman-compose has no `rm`
    # subcommand at all. These four carry a fixed `container_name`, so the compose
    # service name and the container name are the same string.
    #
    # `--depend` is podman-only -- docker rejects the flag, and because the volume
    # removal below cannot proceed while a container still holds it, a silently failed
    # `rm` turns into "volume is in use" several steps later. Fail loudly here instead.
    args = ["rm", "-f"] + (["--depend"] if rt.name == "podman" else []) + TEMPORAL_SERVICES
    run = rt.run(args, capture_output=True, text=True)
    if run.returncode != 0:
        still = rt.run(["ps", "-a", "--format", "{{.Names}}"],
                       capture_output=True, text=True).stdout.split()
        left = [c for c in TEMPORAL_SERVICES if c in still]
        if left:
            fail("could not remove %s: %s" % (", ".join(left), run.stderr.strip()))
    volumes = rt.run(["volume", "ls", "--format", "{{.Name}}"],
                     capture_output=True, text=True).stdout.split()
    doomed = [v for v in volumes if v.startswith(proj + "_")
              and any(v.endswith(sfx) for sfx in TEMPORAL_VOLUME_SUFFIXES)]
    if not doomed:
        print("reset-temporal: no temporal volumes to remove")
    else:
        run = rt.run(["volume", "rm", "-f"] + doomed, capture_output=True, text=True)
        if run.returncode != 0:
            fail("could not remove volumes: %s" % run.stderr.strip())
        for vol in doomed:
            print("reset-temporal: removed volume %s" % vol)
    print("reset-temporal: run ./deploy to re-initialise at %s history shards"
          % cfg.get("main_services", "temporal_history_shards"))


def run_or_fail(cmd):
    print("+ %s" % " ".join(cmd))
    result = subprocess.run(cmd)
    if result.returncode != 0:
        fail("command failed with exit code %d" % result.returncode)


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------

def load_config(args):
    if INI_PATH.exists():
        return Config(INI_PATH)
    if args.print_env or args.print_command:
        print("note: hoover4.ini not found — rendering from hoover4.ini.example "
              "defaults", file=sys.stderr)
        if not INI_EXAMPLE_PATH.exists():
            fail("neither hoover4.ini nor hoover4.ini.example exists")
        return Config(INI_EXAMPLE_PATH)
    fail("hoover4.ini not found. Create it from the tracked template:\n"
         "    cp hoover4.ini.example hoover4.ini && $EDITOR hoover4.ini")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Deploy hoover4 from hoover4.ini.")
    parser.add_argument("--ai-services", action="store_true",
                        help="deploy the ai_services side instead of main_services")
    parser.add_argument("--print-env", action="store_true",
                        help="render and show the .env files, start nothing")
    parser.add_argument("--print-command", action="store_true",
                        help="show the docker compose invocation, run nothing")
    parser.add_argument("--build", action="store_true", help="build images first")
    parser.add_argument("--down", action="store_true",
                        help="compose down for the selected side")
    parser.add_argument("--reset", action="store_true",
                        help="compose down and remove the project's data volumes "
                             "(model caches and Serena are preserved)")
    parser.add_argument("--reset-caches", action="store_true",
                        help="with --reset: also remove the model-cache volumes")
    parser.add_argument("--reset-temporal", action="store_true",
                        help="drop Temporal's history and visibility stores only, "
                             "keeping ClickHouse/Garage/Manticore; required to change "
                             "temporal_history_shards")
    args = parser.parse_args(argv)

    side = "ai" if args.ai_services else "main"
    cfg = load_config(args)
    rt = Runtime()

    if args.print_env:
        env = render_ai_env(cfg) if side == "ai" else render_main_env(cfg)
        path = AI_COMPOSE_DIR / ".env" if side == "ai" else MAIN_COMPOSE_DIR / ".env"
        print("# would write %s:" % path)
        print(ENV_HEADER, end="")
        for key in sorted(env):
            print("%s=%s" % (key, env[key]))
        return 0

    if args.print_command:
        action = ["down"] if args.down else ["up", "-d"] + (["--build", "--force-recreate"] if args.build else [])
        if side == "ai" and not cfg.get_bool("ai_services", "enabled"):
            # Show what WOULD run, but do not let the output imply the tier is
            # deployable: a real `--ai-services` run refuses in the preflights.
            print("note: [ai_services] enabled = false — a real --ai-services run "
                  "refuses; the command below is what it would render if enabled",
                  file=sys.stderr)
        cmd = compose_command(cfg, side, rt, action)
        print(" ".join(cmd))
        if side == "main" and not args.down and cfg.get_bool("main_services", "serena_enabled"):
            print(" ".join(serena_command(cfg, rt, action)))
        return 0

    starting = not (args.down or args.reset or args.reset_temporal)
    run_preflights(cfg, side, rt, starting)

    # Render the generated .env next to the compose files.
    if side == "ai":
        changed = write_env_file(AI_COMPOSE_DIR / ".env", render_ai_env(cfg))
        env_path = AI_COMPOSE_DIR / ".env"
    else:
        changed = write_env_file(MAIN_COMPOSE_DIR / ".env", render_main_env(cfg))
        env_path = MAIN_COMPOSE_DIR / ".env"
    print("rendered %s%s" % (env_path, " (changed)" if changed else " (unchanged)"))

    if args.down:
        compose_down(cfg, side, rt)
        return 0

    if args.reset:
        compose_reset(cfg, side, rt, args.reset_caches)
        return 0

    if args.reset_temporal:
        compose_reset_temporal(cfg, side, rt)
        return 0

    if side == "ai":
        ensure_network(rt, "ai_services")
    else:
        # The main stack's network is declared in the compose file without DNS
        # settings; create/repair it ourselves first so compose finds it already
        # configured. Without this, aardvark-dns forwards to the host's 127.*
        # resolver stub and external DNS is wedged stack-wide.
        ensure_network(rt, "hoover4")
    compose_up(cfg, side, rt, args.build)
    if side == "ai":
        verify_network_dns(rt, cfg, side)
        reprobe_embeddings(rt)
    else:
        # Serena is deployed as its own project, AFTER the main stack: the MCP server
        # the agent talks through must not share a project with anything `down` or
        # `--reset` can select.
        compose_up_serena(cfg, rt, args.build)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except DeployError as exc:
        print("deploy: error: %s" % exc, file=sys.stderr)
        sys.exit(1)
