#!/usr/bin/env bash
# Wire this checkout's shared agent instructions into every harness on this machine.
#
# One source of truth: .agents/. The pieces git carries — the two .claude symlinks and the
# skills, rules and hooks themselves — are already in the checkout. What this script creates
# is the per-harness adapters, which are machine-local and generated rather than tracked.
#
#   ./.agents/bootstrap.sh            report what is wired and what is missing, change nothing
#   ./.agents/bootstrap.sh --apply    create the links and adapter files
#
# Idempotent: re-running changes nothing and prints what it found. Symlinks are used wherever
# a harness follows them, because a copy drifts. Where a harness needs a different file format
# the adapter is generated and carries a banner saying so.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && git rev-parse --show-toplevel)"
HARNESSES="$REPO_ROOT/.agents/harnesses"
APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

note() { printf '  %s\n' "$*"; }
act()  { if [ "$APPLY" = 1 ]; then "$@"; else note "WOULD: $*"; fi }

# link <target-relative-to-the-link> <link-path-relative-to-repo>
link() {
    local target="$1" linkpath="$2"
    local abs="$REPO_ROOT/$linkpath"
    if [ -L "$abs" ]; then
        local current; current="$(readlink "$abs")"
        if [ "$current" = "$target" ]; then note "ok      $linkpath -> $target"; return; fi
        note "RELINK  $linkpath -> $current (want $target)"
        act rm -f "$abs"
    elif [ -e "$abs" ]; then
        note "CONFLICT $linkpath exists and is not a symlink -- left alone, resolve by hand"
        return
    else
        note "MISSING $linkpath"
    fi
    act mkdir -p "$(dirname "$abs")"
    act ln -s "$target" "$abs"
}

echo "repo: $REPO_ROOT"

echo "[1] shared source of truth"
for d in .agents/skills .agents/rules .agents/hooks; do
    if [ -d "$REPO_ROOT/$d" ]; then note "ok      $d"; else note "MISSING $d"; fi
done
# Restoring a checkout on a filesystem that loses the mode bit is the one moment this is
# easy to lose, and a hook that is not executable fails silently as "no hook configured".
for h in "$REPO_ROOT"/.agents/hooks/*; do
    [ -e "$h" ] || continue
    [ -x "$h" ] || { note "not executable: ${h#$REPO_ROOT/}"; act chmod +x "$h"; }
done

echo "[2] Claude Code"
link "../.agents/skills" ".claude/skills"
link "../.agents/rules"  ".claude/rules"
if grep -q 'deny-unscoped-search' "$REPO_ROOT/.claude/settings.json" 2>/dev/null; then
    note "ok      .claude/settings.json declares the hooks"
else
    note "MISSING hooks in .claude/settings.json -- merge the hooks block from"
    note "        .agents/harnesses/claude-settings.json by hand and restart the session."
    note "        A coding agent is deliberately not allowed to edit its own harness config."
fi

echo "[3] opencode"
# opencode reads .agents/skills/<name>/SKILL.md natively -- nothing to link. Only the MCP
# block needs installing.
if [ -f "$REPO_ROOT/opencode.json" ]; then note "ok      opencode.json present"
else note "MISSING opencode.json -- copy .agents/harnesses/opencode.json to the repo root"; fi

echo "[4] Codex"
if [ -f "$REPO_ROOT/.codex/config.toml" ]; then note "ok      .codex/config.toml present"
else note "MISSING .codex/config.toml -- start from .agents/harnesses/codex.toml"; fi
note "Codex reads AGENTS.md at the repo root and does NOT expand @imports: the root file stands alone"

echo "[5] Gemini CLI"
if [ -f "$REPO_ROOT/.gemini/settings.json" ]; then note "ok      .gemini/settings.json present"
else note "MISSING .gemini/settings.json -- start from .agents/harnesses/gemini-settings.json"; fi
# Gemini's context file is GEMINI.md unless the installed build supports naming others.
link "AGENTS.md" "GEMINI.md"

echo "[6] Cursor"
if [ -f "$REPO_ROOT/.cursor/mcp.json" ]; then note "ok      .cursor/mcp.json present"
else note "MISSING .cursor/mcp.json -- start from .agents/harnesses/cursor-mcp.json"; fi
# Cursor rules are .mdc with their own frontmatter; generate, never duplicate.
if [ -d "$REPO_ROOT/.agents/rules" ]; then
    for rule in "$REPO_ROOT"/.agents/rules/*.md; do
        [ -e "$rule" ] || continue
        base="$(basename "$rule" .md)"
        out="$REPO_ROOT/.cursor/rules/$base.mdc"
        if [ "$APPLY" = 1 ]; then
            mkdir -p "$(dirname "$out")"
            {
                echo "---"
                # Carry the shared rule's own paths: line through as Cursor's globs:.
                awk '/^paths:/{print "globs: " substr($0, index($0,$2))} /^description:/{print}' "$rule"
                echo "alwaysApply: false"
                echo "---"
                echo "<!-- generated by .agents/bootstrap.sh from .agents/rules/$base.md; edit that file -->"
                sed '1{/^---$/!q}; 1,/^---$/d' "$rule"
            } > "$out"
            note "wrote   .cursor/rules/$base.mdc"
        else
            note "WOULD generate .cursor/rules/$base.mdc"
        fi
    done
fi

echo "[7] harnesses needing a manual check on this machine"
note "Kimi CLI / Kimi Code: config location and MCP shape not established -- check its own docs"
note "Google Antigravity: config location and MCP shape not established -- check its own docs"

echo
if [ "$APPLY" = 1 ]; then
    echo "applied. now run .agents/verify-wiring.sh"
else
    echo "dry run. re-run with --apply to make these changes."
fi
