#!/usr/bin/env python3
"""Write Cursor agent files from .claude/agents with Cursor model pins."""

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent.parent
HARNESS = ROOT / ".agents" / "harnesses" / "cursor.json"
SOURCE = ROOT / ".claude" / "agents"
DEST = ROOT / ".cursor" / "agents"
ROLES = ("organizer", "executor-light", "executor-heavy", "reviewer")
OBSOLETE_ROLES = ("executor",)
KEEP_KEYS = ("name", "description")
DROP_KEYS = {"model", "effort", "tools"}


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        raise SystemExit("agent file has no frontmatter")
    rest = text[4:]
    end = rest.find("\n---\n")
    if end < 0:
        raise SystemExit("agent file frontmatter is not closed")
    return rest[:end], rest[end + 5 :]


def parse_simple_yaml(block):
    data = {}
    for line in block.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip()
    return data


def yaml_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def render_one(name, harness):
    source = SOURCE / f"{name}.md"
    if not source.is_file():
        raise SystemExit(f"missing agent source: {source}")
    front, body = parse_frontmatter(source.read_text(encoding="utf-8"))
    meta = parse_simple_yaml(front)
    model = harness["models"][name]
    lines = ["---"]
    for key in KEEP_KEYS:
        if key in meta:
            lines.append(f"{key}: {meta[key]}")
    lines.append(f"model: {model}")
    extra = harness.get("agent_extra", {}).get(name) or {}
    for key, value in extra.items():
        lines.append(f"{key}: {yaml_value(value)}")
    lines.append("---")
    lines.append(
        f"<!-- generated by .agents/harnesses/render_cursor_agents.py from .claude/agents/{name}.md; edit that file -->"
    )
    lines.append("")
    return "\n".join(lines) + body


def render_all():
    harness = json.loads(HARNESS.read_text(encoding="utf-8"))
    if set(harness["models"]) != set(ROLES):
        raise SystemExit(f"cursor.json models must name exactly {ROLES}")
    return {name: render_one(name, harness) for name in ROLES}


def write_all(files):
    DEST.mkdir(parents=True, exist_ok=True)
    for name, text in files.items():
        (DEST / f"{name}.md").write_text(text, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="write .cursor/agents")
    parser.add_argument("--check", action="store_true", help="exit 1 when files differ")
    args = parser.parse_args()
    wanted = render_all()
    obsolete = [name for name in OBSOLETE_ROLES if (DEST / f"{name}.md").exists()]
    if args.apply:
        write_all(wanted)
        for name in obsolete:
            (DEST / f"{name}.md").unlink()
        print(f"wrote {len(wanted)} Cursor agent files")
        return 0
    mismatched = []
    for name, text in wanted.items():
        path = DEST / f"{name}.md"
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current != text:
            mismatched.append(name)
    if mismatched or obsolete:
        print("Cursor agent files differ: " + ", ".join(mismatched + obsolete))
        return 1 if args.check else 0
    print("Cursor agent files match")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
